craftingTable.remove(<item:cyclic:emerald_sword>);
craftingTable.remove(<item:cyclic:emerald_shovel>);
craftingTable.remove(<item:cyclic:emerald_boots>);
craftingTable.remove(<item:cyclic:emerald_leggings>);
craftingTable.remove(<item:cyclic:emerald_chestplate>);
craftingTable.remove(<item:cyclic:emerald_helmet>);
craftingTable.remove(<item:cyclic:emerald_pickaxe>);
craftingTable.remove(<item:cyclic:emerald_axe>);
craftingTable.remove(<item:cyclic:emerald_hoe>);
